TRUNCATE TABLE SUNGL.GLA_GLIS_HT02;
TRUNCATE TABLE SUNGL.GLA_GLIS_COUNT;
TRUNCATE TABLE SUNGL.DATA_RJ_BASE;
TRUNCATE TABLE SUNGL.DATA_DAPIN_RESLT;

CALL SUNGL.PKG_ITEM_COUNT_FAC.TAX_COUNT();
CALL SUNGL.PKG_ITEM_COUNT_FAC.COUNT_BRCH_ITEM();
CALL SUNGL.PKG_ITEM_COUNT_FAC.CONVERT_TO_RMB();