CREATE OR REPLACE PROCEDURE PROCESS IS

FILE_NAME VARCHAR2(255);

BEGIN
/**
 * @description: 清理数据
 */

TRUNCATE TABLE SUNGL.GLA_GLIS_HT02;
TRUNCATE TABLE SUNGL.GLA_GLIS_COUNT;
TRUNCATE TABLE SUNGL.DATA_RJ_BASE;
TRUNCATE TABLE SUNGL.DATA_DAPIN_RESLT;

/**
 * @description: 获取日期
 */

FILE_NAME := 'uacp_DAPIN_DATA_'||TO_CHAR(SYSDATE,'YYYMMDD')||'.csv';

/**
 * @description: 汇总计税折算
 */

--价税分离
CALL SUNGL.PKG_ITEM_COUNT_FAC.TAX_COUNT();
--科目机构汇总
CALL SUNGL.PKG_ITEM_COUNT_FAC.COUNT_BRCH_ITEM();
--折算
CALL SUNGL.PKG_ITEM_COUNT_FAC.CONVERT_TO_RMB();
--币种来源汇总
CALL SUNGL.PKG_ITEM_COUNT_FAC.COUNT_CRC_SYS();

/**
 * @description: 指标加工
 */

--加工指标
CALL SUNGL.PKG_ITEM_COUNT_FAC.INSERT_DATA_DAPIN_RESULT();

/**
 * @description: 卸数
 */

--将结果表生成CSV文件放在服务器对应目录，OUT_PATH路径需要预先设置！
CALL SUNGL.PKG_ITEM_COUNT_FAC.SQL_TO_CSV('SELECT * FROM DATA_DAPIN_RESLT','OUT_PATH',FILE_NAME);
--将数据文件通过FTP传输给下游
CALL SUNGL.PKG_ITEM_COUNT_FAC.FTP_TO_DAPIN();

END PROCESS;