CREATE OR REPLACE PACKAGE "SUNGL".PKG_ITEM_COUNT_BILI IS

  -- AUTHOR  : N_ZHOUMINGLE
  -- CREATED : 2022/11/26 11:21:11
  -- PURPOSE : 比例类指标
  
FUNCTION COSTINCO(I_COL NUMBER) RETURN NUMBER;

END PKG_ITEM_COUNT_BILI;
