CREATE OR REPLACE PACKAGE "SUNGL".PKG_ITEM_COUNT_PROCESS IS

  -- AUTHOR  : N_ZHOUMINGLE
  -- CREATED : 2022/11/27 20:59:27
  -- PURPOSE : 大屏数据生成以及推送流程

  PROCEDURE INSERT_DATA_RJ_BASE;
  PROCEDURE INSERT_DATA_DAPIN_RESULT;
  PROCEDURE SQL_TO_CSV(P_QUERY    IN VARCHAR2,
                       P_DIR      IN VARCHAR2,
                       P_FILENAME IN VARCHAR2);
  PROCEDURE FTP_TO_DAPIN;

END PKG_ITEM_COUNT_PROCESS;
