CREATE OR REPLACE PACKAGE "SUNGL".PKG_ITEM_COUNT_FAC IS

  -- AUTHOR  : N_ZHOUMINGLE
  -- CREATED : 2022/11/26 11:21:11
  -- PURPOSE : 科目机构币种来源汇总 价税分离 本位币折算
  
PROCEDURE TAX_COUNT;
PROCEDURE COUNT_BRCH_ITEM;
PROCEDURE CONVERT_TO_RMB;
PROCEDURE COUNT_CRC_SYS;

END PKG_ITEM_COUNT_FAC;